### ISSUE TITLE
3.5 控制流 这章好像显示有问题

### ISSUE THREAD

**Issue by doveq** [rust-lang-cn/book-cn#132]
显示是空白的，切换英文版正常。
https://rustwiki.org/zh-CN/book/ch03-05-control-flow.html
![微信图片_20230213153927](https://user-images.githubusercontent.com/8486761/218398597-7b433294-6489-42fe-b4ba-2b94ac37adf8.png)

**Comment by YangFong** [comment]
抱歉，这是我上一次的 comment 导致的问题。该文件被我移到了另一个文件夹下，感谢你的报告。

**Comment by xiaoyao96** [comment]
我也遇到了同样的问题，请问什么时候修复呀？

**Comment by YangFong** [comment]
> 我也遇到了同样的问题，请问什么时候修复呀？

当前部署存在问题，我无法修复。只能建议，在页面点击编辑，读原生 md 文件。

**Comment by YangFong** [comment]
抱歉，这是一个馊主意，因为这样是看不到实例代码的。这里有一份链接，GitHub page，早期部署的。

https://rust-lang-cn.github.io/book-cn/ch03-05-control-flow.html

**Comment by xiaoyao96** [comment]
> https://rust-lang-cn.github.io/book-cn/ch03-05-control-flow.html

感谢

**Comment by lihaooo** [comment]
似乎这个问题一直没有得到解决

**Comment by YangFong** [comment]
@lihaooo 目前仓库的内容已经更新，但是，[rustwiki.org](rustwiki.org) 无法上传更新，导致到现在为止，依然是内无内容的情况。

也许我需要使用 GitHub Page 保持更新内容可供浏览。

**Comment by aaranxu** [comment]
已更新了。因网站是自动更新的，但是里面有 Git 提交的记录历史被撤销回去，导致更仓库的拉取最新记录失败。

**Comment by aaranxu** [comment]
已更新了。因网站是自动更新的，但是里面有 Git 提交的记录历史被撤销回去，导致更仓库的拉取最新记录失败。
