### ISSUE TITLE
读者反馈

### ISSUE THREAD

**Issue by mogmoug** [rust-lang-cn/book-cn#140]
感觉有写句子读起来不是中文的语序，有点怪怪的

比如
>示例 4-5 中的元组代码有这样一个问题：我们必须将 String 返回给调用函数，以便在调用 calculate_length 后仍能使用 String，因为 String 被移动到了 calculate_length 内。

这个句子应该把因为移到前面去，不然读起来很怪

还有
> 下面是如何定义并使用一个（新的）calculate_length 函数，它以一个对象的引用作为参数而不是获取值的所有权：
> 文件名: src/main.rs
```rust
fn main() {
    let s1 = String::from("hello");

    let len = calculate_length(&s1);

    println!("The length of '{}' is {}.", s1, len);
}

fn calculate_length(s: &String) -> usize {
    s.len()
}
```

那一句话下面就是代码了，可以直接把”如何定义并使用“删去，要不然感觉很奇怪

**Comment by YangFong** [comment]
感谢你的反馈，当前翻译确实存在许多不足之处，我们欢迎 PR 修改。又或者综合一下意见，我来对该段进行优化。

**Comment by mogmoug** [comment]
有问题诶，我参照了下原文，好像少了蛮多东西的，难怪那么难理解

**Comment by mogmoug** [comment]
感觉有些地方不如机翻诶

**Comment by YangFong** [comment]
这一点，你可以理解为版本不同。目前的内容是参考之前版本翻译的，而后原文更新了，但翻译内容未同步更新，所以相比之下，一些内容会显得不合时宜。
