### ISSUE TITLE
定义枚举章节错误

### ISSUE THREAD

**Issue by robotneo** [rust-lang-cn/book-cn#145]
如果使用 None 而不是 Some，需要告诉 Rust Option<T> 是什么类型的，因为编译器只通过 None 值无法推断出 Some 成员保存的值的类型。

应该改为：
如果使用 None 而不是 Some，需要告诉 Rust Option<T> 是什么类型的，因为编译器只通过 None 值无法推断出 None 成员保存的值的类型。

**Comment by YangFong** [comment]
无问题，参见原文：

> the compiler can’t infer the type that the corresponding Some variant will hold by looking only at a None value.

虽然版本不一致，但确实是 Some，而不是：通过 None 值推断 None 成员。
