### ISSUE TITLE
狗屁不通得翻译问题

### ISSUE THREAD

**Issue by 08820048** [rust-lang-cn/book-cn#160]
有一说一，你这翻译还不如机翻，翻译之后狗屁不通，逻辑混乱，一个中国人都不知道你特么在表达什么，早点退役吧你。

**Comment by YangFong** [comment]
嗯，不错，其实看原文最好。原文仓库在这：[https://github.com/rust-lang/book](https://github.com/rust-lang/book)，原文站点在这：[https://doc.rust-lang.org/book/](https://doc.rust-lang.org/book/)。
