### ISSUE TITLE
申请区域更新

### ISSUE THREAD

**Issue by YangFong** [rust-lang-cn/book-cn#45]
这一句在我看来，太混乱了。另外，该区域在原文中有更新（指红框这一句），可以选择更新（并重译）。

![image](https://user-images.githubusercontent.com/70502828/149351975-08950bb4-7721-4369-bb3e-7b74af6a5bd1.png)

**Comment by aaranxu** [comment]
感谢指出，我明天抽空更新下翻译内容。
