### ISSUE TITLE
《19.5 宏》一处翻译不准确的地方

### ISSUE THREAD

**Issue by vichare** [rust-lang-cn/book-cn#58]
原文：
> The #[macro_export] annotation indicates that this macro should be made available whenever the crate in which the macro is defined is brought into scope. 

目前的翻译：
> 无论何时导入定义了宏的包，#[macro_export] 标注说明宏应该是可用的。 

建议的翻译：
> #[macro_export] 标注说明，只要将定义了宏的crate引入作用域，宏就应当是可用的。

首先，这里翻译的语序不准确，至少影响理解。说实话只看翻译文本我完全不理解这句话是什么意思。

第二，crate不应该被翻译成“包”。这里应当区分`crate`和`package`。

第三，应该保留"导入作用域"，因为下一句话：
> Without this annotation, the macro can’t be brought into scope.

指“如果没有该标注，这个宏不能（**随着crate一起**）被引入作用域。”
如果去掉“引入作用域”会影响对下一句话的理解。

**Comment by YangFong** [comment]
感谢指出问题，该改动已提交，但是我并不能确定其中的准确性（并非翻译）。需要等待合适的人员进行下一步的审查

**Comment by ZhangHanDong** [comment]
@vichare  

crate 也是包。 package 表示一个或多个crate。每个 crate 的 Cargo.toml 最上面写的就是 `[package]` 。没有必要区分。

否则，你给 crate 起个什么名字呢？ 「箱体」？ 不建议再造一个大家不熟悉的名字。

此处翻译为 包 也不会影响学习和使用。因为这里说 引入包， 平常开发 rust ，引入的肯定是 crate，不是package。

最多这里加个英文 ，` 包（crate）`

**Comment by vichare** [comment]
crate不需要翻译，只要前后一致就可以。比如第七章的标题是：
> 使用包、Crate和模块管理不断增长的项目

所以直接说crate就可以。不确定这里为什么要将crate翻译成包。

**Comment by ZhangHanDong** [comment]
@vichare  是的，前后要一致

**Comment by YangFong** [comment]
@ZhangHanDong @vichare 那么最后进行一下确认吧，对于 #59 的变动是否可接受，即或者，还有什么需要改进的地方
