### ISSUE TITLE
一个错误

### ISSUE THREAD

**Issue by mcfd** [rust-lang-cn/book-cn#6]
猜数游戏
0.9.0成了0.6.0
中文:如果要使用 rand 版本 0.9.0 或 0.9.x 系列中的任何版本，则必须像这样更新 Cargo.toml 文件：

[dependencies]

----rand = "0.6.0"----
下一次运行 cargo build 时，Cargo 会从 registry 更新可用的 crate，并根据你指定的新版本重新计算。
英文:If you wanted to use rand version 0.9.0 or any version in the 0.9.x series, you’d have to update the Cargo.toml file to look like this instead:

[dependencies]
----rand = "0.9.0"----
The next time you run cargo build, Cargo will update the registry of crates available and reevaluate your rand requirements according to the new version you have specified.

**Comment by ZhangHanDong** [comment]
方便发一下pr吧
