### ISSUE TITLE
book.toml 中 [book] 节下当为 authors 而非 author

### ISSUE THREAD

**Issue by glatavento** [rust-lang-cn/book-cn#66]
见
https://github.com/rust-lang/mdBook/blob/981b79b3b39d80b61da2a10622d6cf611a23686a/src/config.rs#L403-L420

**Comment by YangFong** [comment]
若是这样，其原项目也需要通知改动：https://github.com/rust-lang/book/blob/main/book.toml

**Comment by wendajiang** [comment]
https://github.com/rust-lang/book/pull/3165 上游已经已经合入
