### ISSUE TITLE
The Rust Programming Language 11.2 中文翻译有误

### ISSUE THREAD

**Issue by Autumnal-Joy** [rust-lang-cn/book-cn#78]
# 官方原文

![image](https://user-images.githubusercontent.com/57229631/172094595-abc2338c-882f-4c58-9988-920b9bf363c3.png)

--show-output的功能：

![image](https://user-images.githubusercontent.com/57229631/172095926-5b6d12ad-1613-4cf8-b8d8-39bb6f7c38bd.png)

# 中文翻译

![image](https://user-images.githubusercontent.com/57229631/172094628-31c8fcad-a649-4a1d-83fa-3af8fadcbdaa.png)

--nocapture的功能：

![image](https://user-images.githubusercontent.com/57229631/172095898-97509663-136f-4ceb-8fd2-0d4669619ef2.png)

**Comment by YangFong** [comment]
此段内容需要更新
