### ISSUE TITLE
一个错误的翻译？

### ISSUE THREAD

**Issue by jokerwyt** [rust-lang-cn/book-cn#87]
https://rustwiki.org/zh-CN/book/ch04-02-references-and-borrowing.html
> 这个限制的好处是 Rust 可以在编译时就避免数据竞争。数据竞争（data race）类似于竞态条件，它可由这三个行为造成：
两个或更多指针同时访问同一数据。
至少有一个指针被用来写入数据。
没有同步数据访问的机制。

这三个行为同时发生才会造成data race，而不是单一行为。

**Comment by YangFong** [comment]
存在一定歧义，可优化
